export {
  DeploymentRouter,
  type RoutingStrategy,
  type DeploymentLane,
  type RolloutMode,
  type RetryPolicyConfig,
  type CircuitBreakerConfig,
  type StreamFallbackMode,
  type StreamFallbackPolicyConfig,
  type RegionRoutingConfig,
  type RoutingDeploymentConfig,
  type DeploymentGroupConfig,
  type RoutingConfig,
  type ResolvedDeployment,
  type DeploymentSelection,
  type DeploymentSelectionContext,
  type DeploymentFailure,
  type DeploymentRuntimeState,
  type SelectionDebugDeployment,
  type SelectionDebugSnapshot,
  type RegionEjectionInfo,
} from './router.js';
